<?xml version="1.0" encoding="utf-8"?>
<package>
  <id>InventoryExpress</id>
  <version>1.1.0.0</version>
  <title>Inventardatenbank</title>
  <authors>rene_schwarzer@hotmail.de</authors>
  <license>MIT</license>
  <icon>icon.png</icon>
  <readme>README.md</readme>
  <description>An inventory database for a variety of purposes.</description>
  <tags>inventar webexpress</tags>
  <artifacts>InventoryExpress.dll</artifacts>
  <artifacts>InventoryExpress.QR.dll</artifacts>
  <dependencies>
	<webexpress>1.4.4.0</webexpress>
	<lib>Microsoft.Data.Sqlite.dll</lib>
	<lib>Microsoft.EntityFrameworkCore.Abstractions.dll</lib>
	<lib>Microsoft.EntityFrameworkCore.dll</lib>
	<lib>Microsoft.EntityFrameworkCore.Relational.dll</lib>
	<lib>Microsoft.EntityFrameworkCore.Sqlite.dll</lib>
	<lib>Microsoft.Extensions.DependencyModel.dll</lib>
	<lib>QRCoder.dll</lib>
	<lib>SQLitePCLRaw.batteries_v2.dll</lib>
	<lib>SQLitePCLRaw.core.dll</lib>
	<lib>SQLitePCLRaw.provider.e_sqlite3.dll</lib>
	<runtime>alpine-x64/native/libe_sqlite3.so</runtime>
	<runtime>linux-arm/native/libe_sqlite3.so</runtime>
	<runtime>linux-arm64/native/libe_sqlite3.so</runtime>
	<runtime>linux-armel/native/libe_sqlite3.so</runtime>
	<runtime>linux-mips64/native/libe_sqlite3.so</runtime>
	<runtime>linux-musl-x64/native/libe_sqlite3.so</runtime>
	<runtime>linux-s390x/native/libe_sqlite3.so</runtime>
	<runtime>linux-x64/native/libe_sqlite3.so</runtime>
	<runtime>linux-x86/native/libe_sqlite3.so</runtime>
	<runtime>osx-arm64/native/libe_sqlite3.dylib</runtime>
	<runtime>osx-x64/native/libe_sqlite3.dylib</runtime>
	<runtime>win-arm/native/e_sqlite3.dll</runtime>
	<runtime>win-arm64/native/e_sqlite3.dll</runtime>
	<runtime>win-x64/native/e_sqlite3.dll</runtime>
	<runtime>win-x86/native/e_sqlite3.dll</runtime>
  </dependencies>
</package>